import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import {Toaster } from "react-hot-toast"
// import {AppContextProvider} from "../../src/app/ai/context/AppContext"
import { AppContextProvider } from "./ai/context/AppContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Spereal.AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <AppContextProvider>
        <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster
          toastOptions={
            {
              success: {style:{background: "black", color:"white"}},
              error: {style:{background: "black", color:"white"}}
            }
          }
          ></Toaster>
        {children}
      </body>
    </html>
      </AppContextProvider>


    </ClerkProvider>
    
  );
}
